creator: "Gosmokeless28"
mos: "N/A"
learning_rate: 5e-4
epochs: 250
batch_size: 32
pretrain: LJspeech
dataset_length: "1h 44 mins"
dataset: Speaking of AI (Transcript by Tari Tennyson)
license: "No license"
Validation_Loss: 0.2
architecture: "tacotron2"
vocoder: "hifi-gan"
